#include <stdint.h>
#include <stdlib.h>
#include "keycode_params.h"

#define KEYCODE_DEF(_code, _top, _mid, _btm, _sgl)                                                                     \
    [_code] = {                                                                                                        \
        .code = _code,                                                                                                 \
        .top  = _top,                                                                                                  \
        .mid  = _mid,                                                                                                  \
        .btm  = _btm,                                                                                                  \
        .sgl  = _sgl,                                                                                                  \
    }

#define KEYCODE_SGL_DEF(_code, _sgl) KEYCODE_DEF(_code, "", "", "", _sgl)
#define KEYCODE_MID_DEF(_code, _mid) KEYCODE_DEF(_code, "", _mid, "", "")
#define KEYCODE_SFT_DEF(_code, _top, _btm) KEYCODE_DEF(_code, _top, "", _btm, "")

const struct keycode_param keycode_params[KC_MAX_COUNT] = {
    KEYCODE_SGL_DEF(KC_NO, ""),
    KEYCODE_SGL_DEF(KC_TRNS, ""),
    KEYCODE_SGL_DEF(2, ""),
    KEYCODE_SGL_DEF(3, ""),
    KEYCODE_SGL_DEF(KC_A, "A"),
    KEYCODE_SGL_DEF(KC_B, "B"),
    KEYCODE_SGL_DEF(KC_C, "C"),
    KEYCODE_SGL_DEF(KC_D, "D"),
    KEYCODE_SGL_DEF(KC_E, "E"),
    KEYCODE_SGL_DEF(KC_F, "F"),
    KEYCODE_SGL_DEF(KC_G, "G"),
    KEYCODE_SGL_DEF(KC_H, "H"),
    KEYCODE_SGL_DEF(KC_I, "I"),
    KEYCODE_SGL_DEF(KC_J, "J"),
    KEYCODE_SGL_DEF(KC_K, "K"),
    KEYCODE_SGL_DEF(KC_L, "L"),
    KEYCODE_SGL_DEF(KC_M, "M"),
    KEYCODE_SGL_DEF(KC_N, "N"),
    KEYCODE_SGL_DEF(KC_O, "O"),
    KEYCODE_SGL_DEF(KC_P, "P"),
    KEYCODE_SGL_DEF(KC_Q, "Q"),
    KEYCODE_SGL_DEF(KC_R, "R"),
    KEYCODE_SGL_DEF(KC_S, "S"),
    KEYCODE_SGL_DEF(KC_T, "T"),
    KEYCODE_SGL_DEF(KC_U, "U"),
    KEYCODE_SGL_DEF(KC_V, "V"),
    KEYCODE_SGL_DEF(KC_W, "W"),
    KEYCODE_SGL_DEF(KC_X, "X"),
    KEYCODE_SGL_DEF(KC_Y, "Y"),
    KEYCODE_SGL_DEF(KC_Z, "Z"),
    KEYCODE_SFT_DEF(KC_1, "!", "1"),
    KEYCODE_SFT_DEF(KC_2, "@", "2"),
    KEYCODE_SFT_DEF(KC_3, "#", "3"),
    KEYCODE_SFT_DEF(KC_4, "$", "4"),
    KEYCODE_SFT_DEF(KC_5, "%", "5"),
    KEYCODE_SFT_DEF(KC_6, "^", "6"),
    KEYCODE_SFT_DEF(KC_7, "&", "7"),
    KEYCODE_SFT_DEF(KC_8, "*", "8"),
    KEYCODE_SFT_DEF(KC_9, "(", "9"),
    KEYCODE_SFT_DEF(KC_0, ")", "0"),
    KEYCODE_MID_DEF(KC_ENT, "Ent"),
    KEYCODE_MID_DEF(KC_ESC, "Esc"),
    KEYCODE_MID_DEF(KC_BSPC, "BSPC"),
    KEYCODE_MID_DEF(KC_TAB, "Tab"),
    KEYCODE_MID_DEF(KC_SPC, "Spc"),
    KEYCODE_SFT_DEF(KC_MINS, "_", "-"),
    KEYCODE_SFT_DEF(KC_EQL, "+", "="),
    KEYCODE_SFT_DEF(KC_LBRC, "{", "["),
    KEYCODE_SFT_DEF(KC_RBRC, "}", "]"),
    KEYCODE_SFT_DEF(KC_BSLS, "|", "\\"),
    KEYCODE_MID_DEF(KC_NUHS, "Nuhs"),
    KEYCODE_SFT_DEF(KC_SCLN, ":", ";"),
    KEYCODE_SFT_DEF(KC_QUOT, "\"", "'"),
    KEYCODE_SFT_DEF(KC_GRV, "~", "`"),
    KEYCODE_SFT_DEF(KC_COMM, "<", ","),
    KEYCODE_SFT_DEF(KC_DOT, ">", "."),
    KEYCODE_SFT_DEF(KC_SLSH, "?", "/"),
    KEYCODE_MID_DEF(KC_CAPS, "Caps"),
    KEYCODE_MID_DEF(KC_F1, "F1"),
    KEYCODE_MID_DEF(KC_F2, "F2"),
    KEYCODE_MID_DEF(KC_F3, "F3"),
    KEYCODE_MID_DEF(KC_F4, "F4"),
    KEYCODE_MID_DEF(KC_F5, "F5"),
    KEYCODE_MID_DEF(KC_F6, "F6"),
    KEYCODE_MID_DEF(KC_F7, "F7"),
    KEYCODE_MID_DEF(KC_F8, "F8"),
    KEYCODE_MID_DEF(KC_F9, "F9"),
    KEYCODE_MID_DEF(KC_F10, "F10"),
    KEYCODE_MID_DEF(KC_F11, "F11"),
    KEYCODE_MID_DEF(KC_F12, "F12"),
    KEYCODE_MID_DEF(KC_PSCR, "Pscr"),
    KEYCODE_MID_DEF(KC_SCRL, "Scrl"),
    KEYCODE_MID_DEF(KC_PAUS, "Paus"),
    KEYCODE_MID_DEF(KC_INS, "Ins"),
    KEYCODE_MID_DEF(KC_HOME, "Home"),
    KEYCODE_MID_DEF(KC_PGUP, "PgUp"),
    KEYCODE_MID_DEF(KC_DEL, "Del"),
    KEYCODE_MID_DEF(KC_END, "End"),
    KEYCODE_MID_DEF(KC_PGDN, "PgDn"),
    KEYCODE_MID_DEF(KC_RGHT, "Rght"),
    KEYCODE_MID_DEF(KC_LEFT, "Left"),
    KEYCODE_MID_DEF(KC_DOWN, "Down"),
    KEYCODE_MID_DEF(KC_UP, "Up"),
    KEYCODE_MID_DEF(KC_NUM, "Num"),
    KEYCODE_MID_DEF(KC_PSLS, "/"),
    KEYCODE_MID_DEF(KC_PAST, "*"),
    KEYCODE_MID_DEF(KC_PMNS, "-"),
    KEYCODE_MID_DEF(KC_PPLS, "+"),
    KEYCODE_MID_DEF(KC_PENT, "Ent"),
    KEYCODE_SGL_DEF(KC_P1, "1"),
    KEYCODE_SGL_DEF(KC_P2, "2"),
    KEYCODE_SGL_DEF(KC_P3, "3"),
    KEYCODE_SGL_DEF(KC_P4, "4"),
    KEYCODE_SGL_DEF(KC_P5, "5"),
    KEYCODE_SGL_DEF(KC_P6, "6"),
    KEYCODE_SGL_DEF(KC_P7, "7"),
    KEYCODE_SGL_DEF(KC_P8, "8"),
    KEYCODE_SGL_DEF(KC_P9, "9"),
    KEYCODE_SGL_DEF(KC_P0, "0"),
    KEYCODE_SGL_DEF(KC_PDOT, "."),
    KEYCODE_MID_DEF(KC_NUBS, "Nbus"),
    KEYCODE_MID_DEF(KC_APP, "App"),
    KEYCODE_MID_DEF(KC_KB_POWER, "Pwr"),
    KEYCODE_SGL_DEF(KC_PEQL, "="),
    KEYCODE_MID_DEF(KC_F13, "F13"),
    KEYCODE_MID_DEF(KC_F14, "F14"),
    KEYCODE_MID_DEF(KC_F15, "F15"),
    KEYCODE_MID_DEF(KC_F16, "F16"),
    KEYCODE_MID_DEF(KC_F17, "F17"),
    KEYCODE_MID_DEF(KC_F18, "F18"),
    KEYCODE_MID_DEF(KC_F19, "F19"),
    KEYCODE_MID_DEF(KC_F20, "F20"),
    KEYCODE_MID_DEF(KC_F21, "F21"),
    KEYCODE_MID_DEF(KC_F22, "F22"),
    KEYCODE_MID_DEF(KC_F23, "F23"),
    KEYCODE_MID_DEF(KC_F24, "F24"),
    KEYCODE_MID_DEF(KC_EXEC, "Exec"),
    KEYCODE_MID_DEF(KC_HELP, "Help"),
    KEYCODE_MID_DEF(KC_MENU, "Menu"),
    KEYCODE_MID_DEF(KC_SLCT, "Slct"),
    KEYCODE_MID_DEF(KC_STOP, "Stop"),
    KEYCODE_MID_DEF(KC_AGIN, "Agin"),
    KEYCODE_MID_DEF(KC_UNDO, "UnDo"),
    KEYCODE_MID_DEF(KC_CUT, "Cut"),
    KEYCODE_MID_DEF(KC_COPY, "Copy"),
    KEYCODE_MID_DEF(KC_PSTE, "Pste"),
    KEYCODE_MID_DEF(KC_FIND, "Find"),
    KEYCODE_MID_DEF(KC_KB_MUTE, "Mute"),
    KEYCODE_MID_DEF(KC_KB_VOLUME_UP, "VolU"),
    KEYCODE_MID_DEF(KC_KB_VOLUME_DOWN, "VolD"),
    KEYCODE_MID_DEF(KC_LCAP, "LCap"),
    KEYCODE_MID_DEF(KC_LNUM, "LNum"),
    KEYCODE_MID_DEF(KC_LSCR, "LScr"),
    KEYCODE_SGL_DEF(KC_PCMM, ","),
    KEYCODE_SGL_DEF(KC_KP_EQUAL_AS400, "="),
    KEYCODE_MID_DEF(KC_INT1, "Int1"),
    KEYCODE_MID_DEF(KC_INT2, "Int2"),
    KEYCODE_MID_DEF(KC_INT3, "Int3"),
    KEYCODE_MID_DEF(KC_INT4, "Int4"),
    KEYCODE_MID_DEF(KC_INT5, "Int5"),
    KEYCODE_MID_DEF(KC_INT6, "Int6"),
    KEYCODE_MID_DEF(KC_INT7, "Int7"),
    KEYCODE_MID_DEF(KC_INT8, "Int8"),
    KEYCODE_MID_DEF(KC_INT9, "Int9"),
    KEYCODE_MID_DEF(KC_LNG1, "Lng1"),
    KEYCODE_MID_DEF(KC_LNG2, "Lng2"),
    KEYCODE_MID_DEF(KC_LNG3, "Lng3"),
    KEYCODE_MID_DEF(KC_LNG4, "Lng4"),
    KEYCODE_MID_DEF(KC_LNG5, "Lng5"),
    KEYCODE_MID_DEF(KC_LNG6, "Lng6"),
    KEYCODE_MID_DEF(KC_LNG7, "Lng7"),
    KEYCODE_MID_DEF(KC_LNG8, "Lng8"),
    KEYCODE_MID_DEF(KC_LNG9, "Lng9"),
    KEYCODE_MID_DEF(KC_ERAS, "Eras"),
    KEYCODE_MID_DEF(KC_SYRQ, "SyRq"),
    KEYCODE_MID_DEF(KC_CNCL, "Cncl"),
    KEYCODE_MID_DEF(KC_CLR, "Clr"),
    KEYCODE_MID_DEF(KC_PRIR, "Prir"),
    KEYCODE_MID_DEF(KC_RETN, "Retn"),
    KEYCODE_MID_DEF(KC_SEPR, "Sepr"),
    KEYCODE_MID_DEF(KC_OUT, "Out"),
    KEYCODE_MID_DEF(KC_OPER, "Oper"),
    KEYCODE_MID_DEF(KC_CLAG, "ClAg"),
    KEYCODE_MID_DEF(KC_CRSL, "Crsl"),
    KEYCODE_MID_DEF(KC_EXSL, "Exsl"),
    KEYCODE_MID_DEF(KC_PWR, "Pwr"),
    KEYCODE_MID_DEF(KC_SLEP, "Slep"),
    KEYCODE_MID_DEF(KC_WAKE, "Wake"),
    KEYCODE_MID_DEF(KC_MUTE, "Mute"),
    KEYCODE_MID_DEF(KC_VOLU, "VolU"),
    KEYCODE_MID_DEF(KC_VOLD, "VolD"),
    KEYCODE_MID_DEF(KC_MNXT, "MNxt"),
    KEYCODE_MID_DEF(KC_MPRV, "MPrv"),
    KEYCODE_MID_DEF(KC_MSTP, "MStp"),
    KEYCODE_MID_DEF(KC_MPLY, "MPly"),
    KEYCODE_MID_DEF(KC_MSEL, "MSel"),
    KEYCODE_MID_DEF(KC_EJCT, "MJct"),
    KEYCODE_MID_DEF(KC_MAIL, "Mail"),
    KEYCODE_MID_DEF(KC_CALC, "Calc"),
    KEYCODE_MID_DEF(KC_MYCM, "MyCm"),
    KEYCODE_MID_DEF(KC_WSCH, "WSch"),
    KEYCODE_MID_DEF(KC_WHOM, "WHom"),
    KEYCODE_MID_DEF(KC_WBAK, "WBak"),
    KEYCODE_MID_DEF(KC_WFWD, "WFwd"),
    KEYCODE_MID_DEF(KC_WSTP, "WStp"),
    KEYCODE_MID_DEF(KC_WREF, "WRef"),
    KEYCODE_MID_DEF(KC_WFAV, "WFav"),
    KEYCODE_MID_DEF(KC_MFFD, "MFFd"),
    KEYCODE_MID_DEF(KC_MRWD, "MRwd"),
    KEYCODE_MID_DEF(KC_BRIU, "BriU"),
    KEYCODE_MID_DEF(KC_BRID, "BriD"),
    KEYCODE_MID_DEF(KC_CPNL, "CPnl"),
    KEYCODE_MID_DEF(KC_ASST, "Asst"),
    KEYCODE_MID_DEF(KC_MCTL, "MCtl"),
    KEYCODE_MID_DEF(KC_LPAD, "LPad"),
    KEYCODE_MID_DEF(0xC3, ""),
    KEYCODE_MID_DEF(0xC4, ""),
    KEYCODE_MID_DEF(0xC5, ""),
    KEYCODE_MID_DEF(0xC6, ""),
    KEYCODE_MID_DEF(0xC7, ""),
    KEYCODE_MID_DEF(0xC8, ""),
    KEYCODE_MID_DEF(0xC9, ""),
    KEYCODE_MID_DEF(0xCA, ""),
    KEYCODE_MID_DEF(0xCB, ""),
    KEYCODE_MID_DEF(0xCC, ""), 
    KEYCODE_MID_DEF(KC_MS_U, "MsU"),
    KEYCODE_MID_DEF(KC_MS_D, "MsD"),
    KEYCODE_MID_DEF(KC_MS_L, "MsL"),
    KEYCODE_MID_DEF(KC_MS_R, "MsR"),
    KEYCODE_MID_DEF(KC_BTN1, "Btn1"),
    KEYCODE_MID_DEF(KC_BTN2, "Btn2"),
    KEYCODE_MID_DEF(KC_BTN3, "Btn3"),
    KEYCODE_MID_DEF(KC_BTN4, "Btn4"),
    KEYCODE_MID_DEF(KC_BTN5, "Btn5"),
    KEYCODE_MID_DEF(KC_BTN6, "Btn6"),
    KEYCODE_MID_DEF(KC_BTN7, "Btn7"),
    KEYCODE_MID_DEF(KC_BTN8, "Btn8"),
    KEYCODE_MID_DEF(KC_WH_U, "WhU"),
    KEYCODE_MID_DEF(KC_WH_D, "WhD"),
    KEYCODE_MID_DEF(KC_WH_L, "WhL"),
    KEYCODE_MID_DEF(KC_WH_R, "WhR"),
    KEYCODE_MID_DEF(KC_ACL0, "Acl0"),
    KEYCODE_MID_DEF(KC_ACL1, "Acl1"),
    KEYCODE_MID_DEF(KC_ACL2, "Acl2"),
    KEYCODE_MID_DEF(KC_LCTL, "LCtl"),
    KEYCODE_MID_DEF(KC_LSFT, "LSft"),
    KEYCODE_MID_DEF(KC_LALT, "LAlt"),
    KEYCODE_MID_DEF(KC_LGUI, "LGui"),
    KEYCODE_MID_DEF(KC_RCTL, "RCtl"),
    KEYCODE_MID_DEF(KC_RSFT, "RSft"),
    KEYCODE_MID_DEF(KC_RALT, "RAlt"),
    KEYCODE_MID_DEF(KC_RGUI, "RGui"),
};

const struct keycode_param * keycode_param_random(void)
{
    return &keycode_params[rand() % KC_MAX_COUNT];
}

const struct keycode_param * keycode_param_get(uint32_t keycode)
{
    if(keycode >= KC_MAX_COUNT) {
        return &keycode_params[0];
    }
    return &keycode_params[keycode];
}
